services:
  - type: web
    name: suitesops
    runtime: node
    plan: free
    rootDir: project
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
